export const products = [
  {
    id: 1,
    name: "Samsung Galaxy s7",
    slug: "Samsung-Galaxy-s7",
    company: "SAMSUNG",
    brand: "Samsung",
    img: "/img/product-1.png",
    category: "phones",
    price: 200,
    featured: true,
    inCart: false,
    count: 0,
    total: 0,
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias libero facere aliquid earum atque consequatur laborum, praesentium eaque numquam ipsum porro quam ea maiores impedit illo minima, distinctio magnam quasi quo? Aspernatur officia, eligendi a distinctio sit optio? Odio, corporis.",
  },
  {
    id: 2,
    name: "Redmi Note 7",
    slug: "Redmi-Note-7",
    company: "REDMI",
    brand: "Redmi",
    img: "/img/product-2.png",
    category: "phones",
    price: 1500,
    featured: true,
    inCart: false,
    count: 0,
    total: 0,
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias libero facere aliquid earum atque consequatur laborum, praesentium eaque numquam ipsum porro quam ea maiores impedit illo minima, distinctio magnam quasi quo? Aspernatur officia, eligendi a distinctio sit optio? Odio, corporis.",
  },
  {
    id: 3,
    name: "Huawe Mate",
    slug: "Huawe-Mate",
    company: "HUAWEI",
    brand: "Huawei",
    img: "/img/product-3.png",
    category: "phones",
    price: 789,
    featured: false,
    inCart: true,
    count: 0,
    total: 0,
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias libero facere aliquid earum atque consequatur laborum, praesentium eaque numquam ipsum porro quam ea maiores impedit illo minima, distinctio magnam quasi quo? Aspernatur officia, eligendi a distinctio sit optio? Odio, corporis.",
  },
  {
    id: 4,
    name: "samsung Note 3",
    slug: "samsung-Note-3",
    company: "SAMSUNG",
    brand: "Samsung",
    img: "/img/product-4.png",
    category: "phones",
    price: 178,
    featured: true,
    inCart: false,
    count: 0,
    total: 0,
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias libero facere aliquid earum atque consequatur laborum, praesentium eaque numquam ipsum porro quam ea maiores impedit illo minima, distinctio magnam quasi quo? Aspernatur officia, eligendi a distinctio sit optio? Odio, corporis.",
  },
  {
    id: 5,
    name: "Nike Zoom",
    slug: "Nike-Zoom",
    company: "Nike",
    brand: "nike",
    img: "/img/product-5.jpg",
    category: "shoes",
    price: 98,
    featured: false,
    inCart: false,
    count: 0,
    total: 0,
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias libero facere aliquid earum atque consequatur laborum, praesentium eaque numquam ipsum porro quam ea maiores impedit illo minima, distinctio magnam quasi quo? Aspernatur officia, eligendi a distinctio sit optio? Odio, corporis.",
  },
  {
    id: 6,
    name: "Apple Earpods",
    slug: "Apple-Earpods",
    company: "Apple",
    brand: "apple",
    img: "/img/product-6.jpg",
    category: "phones",
    price: 89,
    featured: false,
    inCart: false,
    count: 0,
    total: 0,
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias libero facere aliquid earum atque consequatur laborum, praesentium eaque numquam ipsum porro quam ea maiores impedit illo minima, distinctio magnam quasi quo? Aspernatur officia, eligendi a distinctio sit optio? Odio, corporis.",
  },
  {
    id: 7,
    name: "Addidas Shirt",
    slug: "Addidas-Shirt",
    company: "Addidas",
    brand: "addidas",
    img: "/img/product-7.jpg",
    category: "clothes",
    price: 245,
    featured: false,
    inCart: false,
    count: 0,
    total: 0,
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias libero facere aliquid earum atque consequatur laborum, praesentium eaque numquam ipsum porro quam ea maiores impedit illo minima, distinctio magnam quasi quo? Aspernatur officia, eligendi a distinctio sit optio? Odio, corporis.",
  },
  {
    id: 8,
    name: "Kofi Shorts",
    slug: "Kofi-Shorts",
    company: "Nike",
    brand: "Nike",
    img: "/img/product-8.jpg",
    category: "clothes",
    price: 289,
    featured: true,
    inCart: false,
    count: 0,
    total: 0,
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias libero facere aliquid earum atque consequatur laborum, praesentium eaque numquam ipsum porro quam ea maiores impedit illo minima, distinctio magnam quasi quo? Aspernatur officia, eligendi a distinctio sit optio? Odio, corporis.",
  },
  {
    id: 9,
    name: "Ladies Gym Wear",
    slug: "Ladies-gym-Wear",
    company: "Nike",
    brand: "Nike",
    img: "/img/product-9.jpg",
    category: "clothes",
    price: 34,
    featured: false,
    inCart: false,
    count: 0,
    total: 0,
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias libero facere aliquid earum atque consequatur laborum, praesentium eaque numquam ipsum porro quam ea maiores impedit illo minima, distinctio magnam quasi quo? Aspernatur officia, eligendi a distinctio sit optio? Odio, corporis.",
  },
  {
    id: 10,
    name: "Ladies Shirt",
    slug: "Ladies-Shirt",
    company: "Addidas",
    brand: "Addidas",
    img: "/img/product-10.jpg",
    category: "clothes",
    price: 134,
    featured: true,
    inCart: true,
    count: 0,
    total: 0,
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias libero facere aliquid earum atque consequatur laborum, praesentium eaque numquam ipsum porro quam ea maiores impedit illo minima, distinctio magnam quasi quo? Aspernatur officia, eligendi a distinctio sit optio? Odio, corporis.",
  },
  {
    id: 11,
    name: "Samsung EarPods",
    slug: "Samsung-EarPods",
    company: "Samsung",
    brand: "Samsung",
    img: "/img/product-11.jpg",
    category: "phones",
    price: 86,
    featured: true,
    inCart: false,
    count: 0,
    total: 0,
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias libero facere aliquid earum atque consequatur laborum, praesentium eaque numquam ipsum porro quam ea maiores impedit illo minima, distinctio magnam quasi quo? Aspernatur officia, eligendi a distinctio sit optio? Odio, corporis.",
  },
  {
    id: 12,
    name: "Addidas Yeezy",
    slug: "Addidas-Yeezy",
    company: "Addidas",
    brand: "Addidas",
    img: "/img/product-12.jpg",
    category: "shoes",
    price: 267,
    featured: false,
    inCart: false,
    count: 0,
    total: 0,
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias libero facere aliquid earum atque consequatur laborum, praesentium eaque numquam ipsum porro quam ea maiores impedit illo minima, distinctio magnam quasi quo? Aspernatur officia, eligendi a distinctio sit optio? Odio, corporis.",
  },
  {
    id: 13,
    name: "Mens Shirt",
    slug: "Mens-Shirt",
    company: "Addidas",
    brand: "Nike",
    img: "/img/product-13.jpg",
    category: "clothes",
    price: 134,
    featured: true,
    inCart: false,
    count: 0,
    total: 0,
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias libero facere aliquid earum atque consequatur laborum, praesentium eaque numquam ipsum porro quam ea maiores impedit illo minima, distinctio magnam quasi quo? Aspernatur officia, eligendi a distinctio sit optio? Odio, corporis.",
  },
  {
    id: 14,
    name: "Nike-Shirt",
    slug: "Nike-Shirt",
    company: "Nike",
    brand: "Nike",
    img: "/img/product-14.jpg",
    category: "clothes",
    price: 108,
    featured: false,
    inCart: false,
    count: 0,
    total: 0,
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias libero facere aliquid earum atque consequatur laborum, praesentium eaque numquam ipsum porro quam ea maiores impedit illo minima, distinctio magnam quasi quo? Aspernatur officia, eligendi a distinctio sit optio? Odio, corporis.",
  },
  {
    id: 15,
    name: "Cotton Shirt",
    slug: "Cotton-Shirt",
    company: "Polo",
    brand: "Polo",
    img: "/img/product-15.jpg",
    category: "clothes",
    price: 124,
    featured: true,
    inCart: false,
    count: 0,
    total: 0,
    details:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias libero facere aliquid earum atque consequatur laborum, praesentium eaque numquam ipsum porro quam ea maiores impedit illo minima, distinctio magnam quasi quo? Aspernatur officia, eligendi a distinctio sit optio? Odio, corporis.",
  },
];

export const categories = [
  {
    id: 1,
    name: "shoes",
    slug: "shoes",
    img: "/img/product-5.jpg",
  },

  {
    id: 2,
    name: "phones",
    slug: "phones",
    img: "/img/product-2.png",
  },
  {
    id: 3,
    name: "clothes",
    slug: "clothes",
    img: "/img/product-15.jpg",
  },
];
